apiVersion: apps/v1
kind: ReplicationController
metadata:
  name: rep-1-meta
  type: front-end
spec:
  template:
    metadata:
    name: rep-pod-meta
    labels:
      type: front-end
    spec:
      containers:
        - name: my
          image: nginx

      replecas: 3

    selector:
      matchlabels:
        type: front-end


